### ISSUE TITLE
versions.txt url has changed

### ISSUE THREAD

**Issue by dylanhilton** [16BitWonder/NX-Update-Checker#10]
# Bug Report

## Switch Environment
N/A

## Describe the Bug
versions.txt no longer exists in the titledb repo, only versions.json in that repo's [root](https://github.com/blawar/titledb/)

**Comment by 16BitWonder** [comment]
I've noticed this too, I'm waiting to see if the next commit brings it back.

I also have plans to switch over to a versions.txt hosted here on this repository in the near future;
If newer commits in titledb don't bring back versions.txt this change will be expedited.

In the meantime, this is the most recent versions.txt from titledb that had version strings (June 29th)
[versions.txt](https://github.com/16BitWonder/NX-Update-Checker/files/4906240/versions.txt)

**Comment by dylanhilton** [comment]
I also know SimonTime from the ReSwitched Discord has indicated they'd expose a web endpoint for their json file.

**Comment by 16BitWonder** [comment]
NX-Update-Checker now pulls from [nx-versions](https://www.github.com/16BitWonder/nx-versions)
https://github.com/16BitWonder/NX-Update-Checker/commit/08f25a085b7c27415abe2125a5fd41e1e94ba958
