### ISSUE TITLE
Issue with The Legend of Zelda: Breath of the Wild + 1.6.0 + 2 DLC // Bad version

### ISSUE THREAD

**Issue by LiloBzH** [16BitWonder/NX-Update-Checker#11]
Hi

Since you soft use your file, there is a problem with Zelda.
App ask new update but there is no update.

After some tests, it's only after installation of 2 DLC

Thank's

**Comment by 16BitWonder** [comment]
(Please use the bug issue template next time)

Can you post a screenshot of the output or send me the produced Available-Updates.txt?

I'm pretty tied for the next couple weeks but I can glance at it.

**Comment by LiloBzH** [comment]
Sorry

File info is : 

```
Generated: 2020/08/01 - 08:23:11 (CEST)
Updates available:

The Legend of Zelda: Breath of the Wild [01007EF00011F002][1.6.0][v0] -> [v196608]
```

Thank you !

**Comment by 16BitWonder** [comment]
01007EF00011F002 is the title ID of the 2nd DLC pack.

Updates for the base game will always have title IDs that end with '800'.
In BOTW's case it would be 01007EF00011E800.

Unlike updates to the base game, DLC don't receive separate updates but rather the DLC binary itself is sometimes updated.

In this case it looks like you're installing v0 of the 2nd DLC pack, however a newer version of it (v196608) is available.

To make sure that is in fact the case, try running [Goldleaf](https://github.com/XorTroll/Goldleaf/releases) and navigating to the following:
```"Manage Console Contents" -> [Pick whichever media BOTW is installed to] -> "The Legend of Zelda: Breath of The Wild" -> "DLC 2"```

The version number displayed should be v196608 like the following if it's up to date:
![2020080110530400-6FC6A735D5C6ECDD3CE4CEBEE31D7F84](https://user-images.githubusercontent.com/25729145/89104264-fc2cfe00-d3e5-11ea-8cff-3c178bb838c3.jpg)

Let me know if the DLC version is up to date and you're still getting the update prompt.

**Comment by LiloBzH** [comment]
good game. You're right, I'm in DLC v0.

**Comment by LiloBzH** [comment]
and its ok with v3 of DLC2

Thank you !
