### ISSUE TITLE
Cash on exit

### ISSUE THREAD

**Issue by evertonstz** [16BitWonder/NX-Update-Checker#12]
# Bug Report
Please fill out as much of the following information as possible, while leaving N/A where you do not have that information.
## Switch Environment
System Version: 10.1.0
Custom Firmware and Version: Atmos 0.13.0
If Atmosphere, are you loading via Hekate's fss0: via primary
Additional sysmodules being loaded: sys-screenuploader

## Describe the Bug
Error code: 2168-0002 (0x4a8)
NX-Update-Checker checks for update fine, but if exiting with home or "+", it'll crash atmosphere.

## To Reproduce
1. open NX-Update-Checker
2. check for update
3. exit, crash happens, sometimes instantly, sometime it'll take a couple seconds.

## Crash Report
4 files seem to be created with the crash, I'm not sure if they're all the same, so I'm posting all of them just in case.
https://pastebin.com/jBaGa7Ds
https://pastebin.com/Mz8Rs5qn
https://pastebin.com/2L3GmTLD
https://pastebin.com/BLCK40zq

**Comment by 16BitWonder** [comment]
Significant changes have been made by now, including recently fixing a null-ref bug that was likely causing this crash.

If you run the latest release (v1.5.1 at the time of writing) and still encounter these crashes please open a new bug report.
