### ISSUE TITLE
Add Ignore Title list

### ISSUE THREAD

**Issue by Conan179** [16BitWonder/NX-Update-Checker#13]
Hello@all.
Is there already a possibility to ignore an installed game when checking so that it no longer appears?
If no, you could add that as a function. would it be possible?

**Comment by 16BitWonder** [comment]
There is currently not a way to ignore installed content.
I could allow folks to have some 'ignored.txt' file in their NX-Update-Checker directory that the app ignores any listed titleIDs from.

**Comment by Conan179** [comment]
The idea with the ignored.txt would take me personally, completely.

**Comment by 16BitWonder** [comment]
Ignoring specific updates/DLC is now possible in df9a633
The README will be updated with instructions to do so.
