### ISSUE TITLE
Add DLC checker

### ISSUE THREAD

**Issue by tatundria** [16BitWonder/NX-Update-Checker#14]
Please, can you add the option to check available DLCs?

**Comment by 16BitWonder** [comment]
On my To do list.
This will make it in eventually but I can't say when, as my hands have been tied for a while now.

**Comment by tatundria** [comment]
Any news on this?

**Comment by 16BitWonder** [comment]
The changes to nx-versions have been made, I will begin working on this and the other [1.5.0](https://github.com/16BitWonder/NX-Update-Checker/projects/4#card-46844596) issues in the next few days.

**Comment by 16BitWonder** [comment]
Missing DLC checking is now available in 0e9cb50
