### ISSUE TITLE
Investigate Potential Crashes when Exiting or Downloading versions.txt

### ISSUE THREAD

**Issue by 16BitWonder** [16BitWonder/NX-Update-Checker#17]
Some users have reported crashing when exiting the app or while downloading versions.txt.

There may be a problem with how we're cleaning up when exiting and the download code may need to be closely reviewed or modified.

**Comment by hrvylein** [comment]
In Atmosphere 0.16.2 and OS 11.0.1 it crashes on every exit. When closing the app via homebutton, my switch crashes on the next opened app/game.

**Comment by 16BitWonder** [comment]
Significant changes have been made, and during recent testing I have not encountered crashes while downloading or exiting.
If they continue to occur the new logging should help address it.
