### ISSUE TITLE
FeatureRequest  Trigger built in update tool

### ISSUE THREAD

**Issue by fennectech** [16BitWonder/NX-Update-Checker#18]
Any chance this can trigger the switch to update the titles with updates from nintendo's own CDN? (Nintndo doesn't automatically do this)  i mean  tell horizon to check for updates on all the apps that have em available

**Comment by fennectech** [comment]
https://switchbrew.org/wiki/NS_Services#RequestUpdateApplication2 Helpful

**Comment by 16BitWonder** [comment]
I'd prefer to keep this as just a tool for checking what needs updated and not trigger any communication/interaction with Nintendo's CDN.

Though if there is interest one could either create a fork that does what you're asking or make a sister-app that reads through any Available-Updates.txt and triggers updates for those titles.
