### ISSUE TITLE
Strange display of installed games/dlc

### ISSUE THREAD

**Issue by hrvylein** [16BitWonder/NX-Update-Checker#19]
As of 11.0.1 and Atmosphere 0.16.2 i see a strange behaviour in detecting available updates. Some DLC or installed updates are displayed like

```
Game [xxx006][10.0.0][v65536] -> [v131072]
Game [xxx007][10.0.0][v0] -> [v65536]
Game [xxx008][10.0.0][v0] -> [v65536]
```

**Comment by hrvylein** [comment]
Maybe I'm wrong and it is related to https://github.com/16BitWonder/NX-Update-Checker/issues/11

**Comment by 16BitWonder** [comment]
Yeah this is akin to #11.

That's just telling you that there exists a newer binary of those DLCs.
I made changes to [nx-versions](https://github.com/16BitWonder/nx-versions) recently to pick up on a lot more DLC so that or a recent update to the DLC may be why it's only showing up now.
