### ISSUE TITLE
NX-Update-Checker v1.5.0 crashes

### ISSUE THREAD

**Issue by death7lord** [16BitWonder/NX-Update-Checker#21]
OFW v11.0.1 , Atmosphère v0.17.0
I don't have a showed folder "....0100D" in my atmosphere\contents\ folder.
https://drive.google.com/file/d/1yM3us3GzX7FVMB9cZuHjSFRpdpbojbWN/view?usp=sharing

**Comment by 16BitWonder** [comment]
There is a bug report template.

Would you mind enabling logging as described in the README:
https://github.com/16BitWonder/NX-Update-Checker#logging

And then sending the produced log?
Also could you try running it with title override instead of in applet mode and see if that makes a difference?

**Comment by death7lord** [comment]
Full mode (via game) - error "The program is closed because happened a error" (I use another language), without fatall error and without restarting of console.
Applet mode - fatall error and restarting of console (look on a previous video).
With a log.flag file it works very slow. Log time: Also no a difference between a two logs.
[NXUC (applet mode).log](https://github.com/16BitWonder/NX-Update-Checker/files/5791947/NXUC.applet.mode.log)
[NXUC (full mode).log](https://github.com/16BitWonder/NX-Update-Checker/files/5791948/NXUC.full.mode.log)

**Comment by 16BitWonder** [comment]
I have reproduced the crash, thank you for your help.
Looking into it, I'll aim to have a hotfix out soon.

**Comment by 16BitWonder** [comment]
I believe I've fixed the issue with this commit: 8da0ca03
Would you mind testing this nightly if you get the chance?

https://dropmefiles.com/MXQOX

**Comment by death7lord** [comment]
Yes! Now it works correctly!! Works exit on "+" button too (was a problems on some previous versions). Also checked "ignore.txt" with international languages on Diablo 3 game, all good.
But I have a small wish. I added ID codes in ignore.txt , but I can forggot what is means an each code. Do you can add functinal to read ID codes into " [ ] " symbols for example? I mean write as:
Diablo III: Eternal Collection UK English Language Pack [01001B300B9BF001]
or
[01001B300B9BF001] Diablo III: Eternal Collection UK English Language Pack
I use Switch-Library-Manager https://github.com/giwty/switch-library-manager for my local libriry and I see an ID and Title name of each missing Update or DLC. And it will be cool if I'll can just copy names (ID and Titles) from Switch-Library-Manager into ignore.txt.

**Comment by 16BitWonder** [comment]
ignore.txt can now have descriptors following the title ID in [v1.5.1](https://github.com/16BitWonder/NX-Update-Checker/releases/tag/v1.5.1).
Please see the [README](https://github.com/16BitWonder/NX-Update-Checker#ignore-list) for additional details.

**Comment by death7lord** [comment]
Ok. Thank you!!
