### ISSUE TITLE
Super Smash Bros. DLC not detected

### ISSUE THREAD

**Issue by tatundria** [16BitWonder/NX-Update-Checker#22]
After installing all the 90 Super Smash Bros. DLC I found that it was not detected by NX-Update-Checker v1.5.2.

**Available-Updates.txt:**

New Updates Available:

New DLC Binaries Available:

Available DLC Not Installed:

Super Smash Bros. Ultimate [01006A800016F009][v131072]
Super Smash Bros. Ultimate [01006A800016F00A][v0]
Super Smash Bros. Ultimate [01006A800016F00B][v0]
Super Smash Bros. Ultimate [01006A800016F00C][v0]
Super Smash Bros. Ultimate [01006A800016F015][v65536]
Super Smash Bros. Ultimate [01006A800016F016][v0]
Super Smash Bros. Ultimate [01006A800016F01F][v0]
Super Smash Bros. Ultimate [01006A800016F020][v0]
Super Smash Bros. Ultimate [01006A800016F021][v0]
Super Smash Bros. Ultimate [01006A800016F022][v0]
Super Smash Bros. Ultimate [01006A800016F023][v0]
Super Smash Bros. Ultimate [01006A800016F024][v0]
Super Smash Bros. Ultimate [01006A800016F025][v0]
Super Smash Bros. Ultimate [01006A800016F026][v0]
Super Smash Bros. Ultimate [01006A800016F027][v0]
Super Smash Bros. Ultimate [01006A800016F028][v0]
Super Smash Bros. Ultimate [01006A800016F029][v0]
Super Smash Bros. Ultimate [01006A800016F02A][v0]
Super Smash Bros. Ultimate [01006A800016F02B][v0]
Super Smash Bros. Ultimate [01006A800016F02C][v0]
Super Smash Bros. Ultimate [01006A800016F02D][v0]
Super Smash Bros. Ultimate [01006A800016F02E][v0]
Super Smash Bros. Ultimate [01006A800016F02F][v0]
Super Smash Bros. Ultimate [01006A800016F030][v0]
Super Smash Bros. Ultimate [01006A800016F031][v0]
Super Smash Bros. Ultimate [01006A800016F032][v0]
Super Smash Bros. Ultimate [01006A800016F033][v0]
Super Smash Bros. Ultimate [01006A800016F034][v0]
Super Smash Bros. Ultimate [01006A800016F035][v0]
Super Smash Bros. Ultimate [01006A800016F036][v0]
Super Smash Bros. Ultimate [01006A800016F037][v0]
Super Smash Bros. Ultimate [01006A800016F038][v0]
Super Smash Bros. Ultimate [01006A800016F039][v0]
Super Smash Bros. Ultimate [01006A800016F03A][v0]
Super Smash Bros. Ultimate [01006A800016F03B][v0]
Super Smash Bros. Ultimate [01006A800016F03C][v0]
Super Smash Bros. Ultimate [01006A800016F03D][v0]
Super Smash Bros. Ultimate [01006A800016F03E][v0]
Super Smash Bros. Ultimate [01006A800016F03F][v0]
Super Smash Bros. Ultimate [01006A800016F040][v0]
Super Smash Bros. Ultimate [01006A800016F041][v0]
Super Smash Bros. Ultimate [01006A800016F042][v0]
Super Smash Bros. Ultimate [01006A800016F043][v0]
Super Smash Bros. Ultimate [01006A800016F044][v0]
Super Smash Bros. Ultimate [01006A800016F045][v0]
Super Smash Bros. Ultimate [01006A800016F046][v0]
Super Smash Bros. Ultimate [01006A800016F047][v0]
Super Smash Bros. Ultimate [01006A800016F065][v0]
Super Smash Bros. Ultimate [01006A800016F066][v0]
Super Smash Bros. Ultimate [01006A800016F067][v0]
Super Smash Bros. Ultimate [01006A800016F068][v0]
Super Smash Bros. Ultimate [01006A800016F069][v0]
Super Smash Bros. Ultimate [01006A800016F06A][v0]
Super Smash Bros. Ultimate [01006A800016F06B][v0]
Super Smash Bros. Ultimate [01006A800016F06C][v0]
Super Smash Bros. Ultimate [01006A800016F06D][v0]
Super Smash Bros. Ultimate [01006A800016F06E][v0]
Super Smash Bros. Ultimate [01006A800016F06F][v0]
Super Smash Bros. Ultimate [01006A800016F070][v0]
Super Smash Bros. Ultimate [01006A800016F071][v0]
Super Smash Bros. Ultimate [01006A800016F072][v0]
Super Smash Bros. Ultimate [01006A800016F073][v0]
Super Smash Bros. Ultimate [01006A800016F077][v0]
Super Smash Bros. Ultimate [01006A800016F078][v0]
Super Smash Bros. Ultimate [01006A800016F079][v0]
Super Smash Bros. Ultimate [01006A800016F07A][v0]
Super Smash Bros. Ultimate [01006A800016F07B][v0]
Super Smash Bros. Ultimate [01006A800016F07C][v0]
Super Smash Bros. Ultimate [01006A800016F07D][v0]
Super Smash Bros. Ultimate [01006A800016F07E][v0]
Super Smash Bros. Ultimate [01006A800016F07F][v0]
Super Smash Bros. Ultimate [01006A800016F080][v0]
Super Smash Bros. Ultimate [01006A800016F081][v0]
Super Smash Bros. Ultimate [01006A800016F082][v0]
Super Smash Bros. Ultimate [01006A800016F169][v0]
Super Smash Bros. Ultimate [01006A800016F16A][v0]
Super Smash Bros. Ultimate [01006A800016F16B][v0]
Super Smash Bros. Ultimate [01006A800016F16C][v0]
Super Smash Bros. Ultimate [01006A800016F16D][v0]
Super Smash Bros. Ultimate [01006A800016F16E][v0]
Super Smash Bros. Ultimate [01006A800016F16F][v0]
Super Smash Bros. Ultimate [01006A800016F170][v0]
Super Smash Bros. Ultimate [01006A800016F171][v0]
Super Smash Bros. Ultimate [01006A800016F172][v0]
Super Smash Bros. Ultimate [01006A800016F173][v0]
Super Smash Bros. Ultimate [01006A800016F174][v0]
Super Smash Bros. Ultimate [01006A800016F175][v0]
Super Smash Bros. Ultimate [01006A800016F176][v0]
Super Smash Bros. Ultimate [01006A800016F177][v0]
Super Smash Bros. Ultimate [01006A800016F178][v0]
Super Smash Bros. Ultimate [01006A800016F179][v0]
Super Smash Bros. Ultimate [01006A800016F17A][v0]

**Comment by 16BitWonder** [comment]
It's funny you point this out, I was just noticing this and investigating it.
I'll see if I can't get a fix out tonight or tomorrow. ^^

**Comment by 16BitWonder** [comment]
Fixed in [v1.5.3](https://github.com/16BitWonder/NX-Update-Checker/releases/tag/v1.5.3) / 41e1b9c2

**Comment by Conan179** [comment]
I have the same problem, even with the latest version it is displayed as follows:

Generated: 2021/02/08 - 21:34:17 (CET)


New Updates Available:

Pokémon Schwert [0100ABF008968800][1.3.0][v327680] -> [v393216]
DORAEMON STORY OF SEASONS [010073700E412800][1.0.2][v131072] -> [v196608]


New DLC Binaries Available:



Available DLC Not Installed:

Super Smash Bros. Ultimate [01006A800016F029][v0]
Super Smash Bros. Ultimate [01006A800016F02A][v0]
Super Smash Bros. Ultimate [01006A800016F02B][v0]
Super Smash Bros. Ultimate [01006A800016F02C][v0]
Super Smash Bros. Ultimate [01006A800016F02D][v0]
Super Smash Bros. Ultimate [01006A800016F02E][v0]
Super Smash Bros. Ultimate [01006A800016F02F][v0]
Super Smash Bros. Ultimate [01006A800016F030][v0]
Super Smash Bros. Ultimate [01006A800016F031][v0]
Super Smash Bros. Ultimate [01006A800016F032][v0]
Super Smash Bros. Ultimate [01006A800016F033][v0]
Super Smash Bros. Ultimate [01006A800016F034][v0]
Super Smash Bros. Ultimate [01006A800016F035][v0]
Super Smash Bros. Ultimate [01006A800016F036][v0]
Super Smash Bros. Ultimate [01006A800016F037][v0]
Super Smash Bros. Ultimate [01006A800016F038][v0]
Super Smash Bros. Ultimate [01006A800016F039][v0]
Super Smash Bros. Ultimate [01006A800016F03A][v0]
Super Smash Bros. Ultimate [01006A800016F03B][v0]
Super Smash Bros. Ultimate [01006A800016F03C][v0]
Super Smash Bros. Ultimate [01006A800016F03D][v0]
Super Smash Bros. Ultimate [01006A800016F03E][v0]
Super Smash Bros. Ultimate [01006A800016F03F][v0]
Super Smash Bros. Ultimate [01006A800016F040][v0]
Super Smash Bros. Ultimate [01006A800016F041][v0]
Super Smash Bros. Ultimate [01006A800016F042][v0]
Super Smash Bros. Ultimate [01006A800016F043][v0]
Super Smash Bros. Ultimate [01006A800016F044][v0]
Super Smash Bros. Ultimate [01006A800016F045][v0]
Super Smash Bros. Ultimate [01006A800016F046][v0]
Super Smash Bros. Ultimate [01006A800016F047][v0]
Super Smash Bros. Ultimate [01006A800016F07E][v0]
Super Smash Bros. Ultimate [01006A800016F07F][v0]
Super Smash Bros. Ultimate [01006A800016F080][v0]
Super Smash Bros. Ultimate [01006A800016F081][v0]
Super Smash Bros. Ultimate [01006A800016F082][v0]
Super Smash Bros. Ultimate [01006A800016F169][v0]
Super Smash Bros. Ultimate [01006A800016F16A][v0]
Super Smash Bros. Ultimate [01006A800016F16B][v0]
Super Smash Bros. Ultimate [01006A800016F16C][v0]
Super Smash Bros. Ultimate [01006A800016F16D][v0]
Super Smash Bros. Ultimate [01006A800016F16E][v0]
Super Smash Bros. Ultimate [01006A800016F16F][v0]
Super Smash Bros. Ultimate [01006A800016F170][v0]
Super Smash Bros. Ultimate [01006A800016F171][v0]
Super Smash Bros. Ultimate [01006A800016F172][v0]
Super Smash Bros. Ultimate [01006A800016F173][v0]
Super Smash Bros. Ultimate [01006A800016F174][v0]
Super Smash Bros. Ultimate [01006A800016F175][v0]
Super Smash Bros. Ultimate [01006A800016F176][v0]
Super Smash Bros. Ultimate [01006A800016F177][v0]
Super Smash Bros. Ultimate [01006A800016F178][v0]
Super Smash Bros. Ultimate [01006A800016F179][v0]
Super Smash Bros. Ultimate [01006A800016F17A][v0]


But they are installed.

**Comment by 16BitWonder** [comment]
I and a couple others have noticed this and it slipped my mind to append it here, my apologies.

DLC 01006A800016F169 through 01006A800016F17A are currently indexed by titledb (one of the sources nx-versions scrapes) but are not released yet.
If I had to guess they're placeholder for future DLC, you cannot have them installed because they're not obtainable.
If it's bothersome seeing them at the moment I would advise adding them to your [ignore list](https://github.com/16BitWonder/NX-Update-Checker#ignore-list).

As for 01006A800016F029 through 01006A800016F047 and 01006A800016F07E through 01006A800016F082 I am fairly confident you do not have those installed. Please double-check if they are listed under Smash Bros. in Goldleaf or any other title manager that can view add-ons for titles.
If you've checked and they are listed as installed then please [enable logging](https://github.com/16BitWonder/NX-Update-Checker#logging) and paste the produced log here.

**Comment by Conan179** [comment]
@16BitWonder I reinstalled my dlcs, either something went wrong during the reinstallation or they were not reinstalled, now it looks like this:
Super Smash Bros. Ultimate [01006A800016F07E][v0]
Super Smash Bros. Ultimate [01006A800016F07F][v0]
Super Smash Bros. Ultimate [01006A800016F080][v0]
Super Smash Bros. Ultimate [01006A800016F081][v0]
Super Smash Bros. Ultimate [01006A800016F082][v0]
Super Smash Bros. Ultimate [01006A800016F169][v0]
Super Smash Bros. Ultimate [01006A800016F16A][v0]
Super Smash Bros. Ultimate [01006A800016F16B][v0]
Super Smash Bros. Ultimate [01006A800016F16C][v0]
Super Smash Bros. Ultimate [01006A800016F16D][v0]
Super Smash Bros. Ultimate [01006A800016F16E][v0]
Super Smash Bros. Ultimate [01006A800016F16F][v0]
Super Smash Bros. Ultimate [01006A800016F170][v0]
Super Smash Bros. Ultimate [01006A800016F171][v0]
Super Smash Bros. Ultimate [01006A800016F172][v0]
Super Smash Bros. Ultimate [01006A800016F173][v0]
Super Smash Bros. Ultimate [01006A800016F174][v0]
Super Smash Bros. Ultimate [01006A800016F175][v0]
Super Smash Bros. Ultimate [01006A800016F176][v0]
Super Smash Bros. Ultimate [01006A800016F177][v0]
Super Smash Bros. Ultimate [01006A800016F178][v0]
Super Smash Bros. Ultimate [01006A800016F179][v0]
Super Smash Bros. Ultimate [01006A800016F17A][v0]

**Comment by 16BitWonder** [comment]
@Conan179
Putting 01006A800016F169 through 01006A800016F17A aside, the only ones left that can be obtained are 01006A800016F07E through 01006A800016F082.

For anyone coming to this issue in the future these are:
01006A800016F07E - Spirit Board Challenge Pack 7 - 1
01006A800016F07F - Spirit Board Challenge Pack 7 - 2
01006A800016F080 - Spirit Board Challenge Pack 7 - 3
01006A800016F081 - Spirit Board Challenge Pack 7 - 4
01006A800016F082 - Spirit Board Challenge Pack 7 - 5
These required Nintendo Switch Online to acquire when they were available.
Iirc you need an unlocker for them now.

**Comment by Conan179** [comment]
Ok, thanks for the Help :)

**Comment by Kraptinkush** [comment]
> After installing all the 90 Super Smash Bros. DLC I found that it was not detected by NX-Update-Checker v1.5.2.
> 
> **Available-Updates.txt:**
> 
> New Updates Available:
> 
> New DLC Binaries Available:
> 
> Available DLC Not Installed:
> 
> Super Smash Bros. Ultimate [01006A800016F009][v131072] Super Smash Bros. Ultimate [01006A800016F00A][v0] Super Smash Bros. Ultimate [01006A800016F00B][v0] Super Smash Bros. Ultimate [01006A800016F00C][v0] Super Smash Bros. Ultimate [01006A800016F015][v65536] Super Smash Bros. Ultimate [01006A800016F016][v0] Super Smash Bros. Ultimate [01006A800016F01F][v0] Super Smash Bros. Ultimate [01006A800016F020][v0] Super Smash Bros. Ultimate [01006A800016F021][v0] Super Smash Bros. Ultimate [01006A800016F022][v0] Super Smash Bros. Ultimate [01006A800016F023][v0] Super Smash Bros. Ultimate [01006A800016F024][v0] Super Smash Bros. Ultimate [01006A800016F025][v0] Super Smash Bros. Ultimate [01006A800016F026][v0] Super Smash Bros. Ultimate [01006A800016F027][v0] Super Smash Bros. Ultimate [01006A800016F028][v0] Super Smash Bros. Ultimate [01006A800016F029][v0] Super Smash Bros. Ultimate [01006A800016F02A][v0] Super Smash Bros. Ultimate [01006A800016F02B][v0] Super Smash Bros. Ultimate [01006A800016F02C][v0] Super Smash Bros. Ultimate [01006A800016F02D][v0] Super Smash Bros. Ultimate [01006A800016F02E][v0] Super Smash Bros. Ultimate [01006A800016F02F][v0] Super Smash Bros. Ultimate [01006A800016F030][v0] Super Smash Bros. Ultimate [01006A800016F031][v0] Super Smash Bros. Ultimate [01006A800016F032][v0] Super Smash Bros. Ultimate [01006A800016F033][v0] Super Smash Bros. Ultimate [01006A800016F034][v0] Super Smash Bros. Ultimate [01006A800016F035][v0] Super Smash Bros. Ultimate [01006A800016F036][v0] Super Smash Bros. Ultimate [01006A800016F037][v0] Super Smash Bros. Ultimate [01006A800016F038][v0] Super Smash Bros. Ultimate [01006A800016F039][v0] Super Smash Bros. Ultimate [01006A800016F03A][v0] Super Smash Bros. Ultimate [01006A800016F03B][v0] Super Smash Bros. Ultimate [01006A800016F03C][v0] Super Smash Bros. Ultimate [01006A800016F03D][v0] Super Smash Bros. Ultimate [01006A800016F03E][v0] Super Smash Bros. Ultimate [01006A800016F03F][v0] Super Smash Bros. Ultimate [01006A800016F040][v0] Super Smash Bros. Ultimate [01006A800016F041][v0] Super Smash Bros. Ultimate [01006A800016F042][v0] Super Smash Bros. Ultimate [01006A800016F043][v0] Super Smash Bros. Ultimate [01006A800016F044][v0] Super Smash Bros. Ultimate [01006A800016F045][v0] Super Smash Bros. Ultimate [01006A800016F046][v0] Super Smash Bros. Ultimate [01006A800016F047][v0] Super Smash Bros. Ultimate [01006A800016F065][v0] Super Smash Bros. Ultimate [01006A800016F066][v0] Super Smash Bros. Ultimate [01006A800016F067][v0] Super Smash Bros. Ultimate [01006A800016F068][v0] Super Smash Bros. Ultimate [01006A800016F069][v0] Super Smash Bros. Ultimate [01006A800016F06A][v0] Super Smash Bros. Ultimate [01006A800016F06B][v0] Super Smash Bros. Ultimate [01006A800016F06C][v0] Super Smash Bros. Ultimate [01006A800016F06D][v0] Super Smash Bros. Ultimate [01006A800016F06E][v0] Super Smash Bros. Ultimate [01006A800016F06F][v0] Super Smash Bros. Ultimate [01006A800016F070][v0] Super Smash Bros. Ultimate [01006A800016F071][v0] Super Smash Bros. Ultimate [01006A800016F072][v0] Super Smash Bros. Ultimate [01006A800016F073][v0] Super Smash Bros. Ultimate [01006A800016F077][v0] Super Smash Bros. Ultimate [01006A800016F078][v0] Super Smash Bros. Ultimate [01006A800016F079][v0] Super Smash Bros. Ultimate [01006A800016F07A][v0] Super Smash Bros. Ultimate [01006A800016F07B][v0] Super Smash Bros. Ultimate [01006A800016F07C][v0] Super Smash Bros. Ultimate [01006A800016F07D][v0] Super Smash Bros. Ultimate [01006A800016F07E][v0] Super Smash Bros. Ultimate [01006A800016F07F][v0] Super Smash Bros. Ultimate [01006A800016F080][v0] Super Smash Bros. Ultimate [01006A800016F081][v0] Super Smash Bros. Ultimate [01006A800016F082][v0] Super Smash Bros. Ultimate [01006A800016F169][v0] Super Smash Bros. Ultimate [01006A800016F16A][v0] Super Smash Bros. Ultimate [01006A800016F16B][v0] Super Smash Bros. Ultimate [01006A800016F16C][v0] Super Smash Bros. Ultimate [01006A800016F16D][v0] Super Smash Bros. Ultimate [01006A800016F16E][v0] Super Smash Bros. Ultimate [01006A800016F16F][v0] Super Smash Bros. Ultimate [01006A800016F170][v0] Super Smash Bros. Ultimate [01006A800016F171][v0] Super Smash Bros. Ultimate [01006A800016F172][v0] Super Smash Bros. Ultimate [01006A800016F173][v0] Super Smash Bros. Ultimate [01006A800016F174][v0] Super Smash Bros. Ultimate [01006A800016F175][v0] Super Smash Bros. Ultimate [01006A800016F176][v0] Super Smash Bros. Ultimate [01006A800016F177][v0] Super Smash Bros. Ultimate [01006A800016F178][v0] Super Smash Bros. Ultimate [01006A800016F179][v0] Super Smash Bros. Ultimate [01006A800016F17A][v0]
