### ISSUE TITLE
incognito issues

### ISSUE THREAD

**Issue by blawar** [16BitWonder/NX-Update-Checker#25]
> If you're having issues downloading the latest versions.txt and you have blanked your prodinfo with something other than Atmosphere's exosphere blanking, please switch to it and test again before opening an issue.

Just do what everyone else does, and revert the libcurl package or fork it.  There was no need for devkitpro to switch the libcurl package to use the switch's SSL module (which is what causes your incognito problems).  I can link you to a fork that still works if you need it.

**Comment by 16BitWonder** [comment]
Yeah I'm not exactly sure why I switched to the newer package if the old one was working fine.
I'm loosely working on a new minor release before a big refactor, I'll start building with the older libcurl package again when I get that out.

**Comment by 16BitWonder** [comment]
Building with reverted libcurl as of [v1.5.4](https://github.com/16BitWonder/NX-Update-Checker/releases/tag/v1.5.4)
