### ISSUE TITLE
ignore.txt ask

### ISSUE THREAD

**Issue by Bubblebuy123** [16BitWonder/NX-Update-Checker#26]
Hello, I write with the google translator. I'm not very good at writing in English.
I created an ignore.txt file and it works quite well. However, 3 things are still displayed to me and I wanted to ask whether I entered it incorrectly or something.
Kind regards
[Available-Updates.txt](https://github.com/16BitWonder/NX-Update-Checker/files/7791842/Available-Updates.txt)
[ignore.txt](https://github.com/16BitWonder/NX-Update-Checker/files/7791843/ignore.txt)

**Comment by 16BitWonder** [comment]
Try your ignore.txt without new lines.
If I recall correctly they may not be separated by new lines.

[ignore.txt](https://github.com/16BitWonder/NX-Update-Checker/files/7794008/ignore.txt)

**Comment by Bubblebuy123** [comment]
ah now there is nothing in "Available Updates" that had been divided into separate lines for the optics. Thanks anyway and a happy new year. Subject can be closed.
