### ISSUE TITLE
Feature request: Blacklist option manually by TID

### ISSUE THREAD

**Issue by JrRadiant** [16BitWonder/NX-Update-Checker#27]
Hello, dear mr. 16BitWonder!..

Is it real to make a blacklist option to manual disable some games from being presented in a new updates / DLC list?

For example: there is a game, Pokemon Cafe Mix. And it's requires online after the update v786432, so after that patch the game cannot be run in offline mode, it's online only. With the patch v786432 (1.100.0), it's completely OK without the need of internet connection.

So every time I use nx-update-checker the program tells me there's an update for Pokemon Cafe Mix, but I don't need it at all. Maybe, you can make an option to manually disable games that one doesn't need to check for updates and/or DLCs, like this:
```
/switch/nx-update-checker/blacklist.txt:

; blacklisted update for games by their TitleID:
[blacklist-update]
010072400E04A000

; blacklisted DLCs for games by their TitleID:
[blacklist-DLC]
010072400E04A000
```

Hope you stay well!
Thanks in advance for your answer.

**Comment by 16BitWonder** [comment]
As fortune would have it there already is an ignore-list functionality:
https://github.com/16BitWonder/NX-Update-Checker#ignore-list

You would place an "ignore.txt" in the same directory as your NRO and populate it with:
```
010072400E04A800 Pokemon Cafe Mix
```

Make sure to use 010072400E04A800 (the update titleID) and not the base game titleID (010072400E04A000)

**Comment by JrRadiant** [comment]
Thank you!
