### ISSUE TITLE
Checking updates without installing the games

### ISSUE THREAD

**Issue by mspykerez** [16BitWonder/NX-Update-Checker#29]
Would it be possible to make a windows application of this tool to check missing updates/dlc from a pointed local folder in our hard drive, like scanning a directory for NSP, NSZ, XCI and XCZ files and look for missing updates there matching the scanned files.
This because due to limited space on the Switch many people often uninstall or restrain themselves from installing some games but keep the game files saved on their PC and in the meantime you can't tell if there were any new updates or DLC released for them that you might want to check out (not until you install the games on the Switch).

It would even be nice if you could just scan the game files present on your Switch SD Card that you have not yet installed.

**Comment by 16BitWonder** [comment]
See https://github.com/16BitWonder/NX-Update-Checker/issues/8

**Comment by mspykerez** [comment]
I see you suggested using Switch Backup Manager but it hasn't been updated in years and I don't think it will accurately report things.

There is the more recent alternative https://github.com/giwty/switch-library-manager but since it relies on blawar's titledb as its only source for data I can confirm that it is definitely suffering from the issue reported here https://github.com/16BitWonder/NX-Update-Checker/issues/28 Although I reported this to the devs in question so far nothing has been done.

Switch Library Manager grabs all the data automatically upon startup from blawar's titledb but it appears to grab it in a different way than you do because the file it generates from it to check missing files against is on a different format than the one from here https://github.com/16BitWonder/nx-versions and I have no idea if it would be possible to make Switch Library Manager work with https://github.com/16BitWonder/nx-versions If you have any hints would be most appreciated!

I suppose it wouldn't be any easier to make NX-Update-Checker able to scan for missing files from the Switch itself that are on the SD Card without needing to install anything thus no separate windows app would be needed? Not an ideal solution but better than nothing!
