### ISSUE TITLE
Dev branch ready for production?

### ISSUE THREAD

**Issue by ghost** [16BitWonder/NX-Update-Checker#34]
Hi, I noticed the dev branch and saw that it had some changes deviating from the master branch and that it has been updated from v1.5.4 to v2.0.0 but hasn't been touched since August of last year. I tried building it myself, but no luck, as I'm new to the whole Switch-Dev building situation. Is the dev branch ready to be used regulary or should we stick to the one in the master branch? Just wondering if it's stable enough so that I can continue trying to build it, or if I should just use the last one posted in "Releases" for the time being.

**Comment by 16BitWonder** [comment]
You should stick to v1.5.4 in releases.
I did some initial changes in the dev branch for whenever I pick this project up again for a big rewrite/GUI implementation. I'm not sure when that will be though.

I'll add a note into the dev branch's README saying to stick to v1.5.4 for now too, sorry about the confusion and building issues.
