### ISSUE TITLE
Working Status on Skyline and Android

### ISSUE THREAD

**Issue by TheMercenary333** [16BitWonder/NX-Update-Checker#35]
Is there any way to run the "NX-Update-Checker" software on Skyline?
Is it possible to bring an update to work within Android (Termux) and Skyline emulator?

**Comment by 16BitWonder** [comment]
> Is there any way to run the "NX-Update-Checker" software on Skyline?

To my knowledge, no.
I would be surprised if it worked there.

> Is it possible to bring an update to work within Android (Termux) and Skyline emulator?

No, this app will only officially support/test for real consoles.
Emulators likely store update info differently (if at all) and someone would probably need to write a separate app or make a pull request for that feature directly into the emulator.
