### ISSUE TITLE
NX-Update-Checker crashes during version comparison

### ISSUE THREAD

**Issue by ChuckNorris9939** [16BitWonder/NX-Update-Checker#9]
# Bug Report
Please fill out as much of the following information as possible, while leaving N/A where you do not have that information.
## Switch Environment
System Version: 10.0.4
Custom Firmware and Version: Athmosphere 0.13.0
If Atmosphere, are you loading via Hekate's fss0: yes
Additional sysmodules being loaded: 
sys-con
sys-clk
tesla
## Describe the Bug
Please give a detailed description of the bug that you are encountering, including the error code if one is being provided (Something like 2168-0002 or 0xFFE) :

## To Reproduce
Please outline the steps below to reproduce this issue:

1. ... I Used NX-Update-Checker multiple times without any crashes
2. ... I installed some updates and used it again without any crashes
3. ... Installed more updates. Used it again and it crashed at this point (without any Error Code)

![01593182335_01000320000cc000](https://user-images.githubusercontent.com/8191872/85870791-d3558f80-b7cd-11ea-8984-c8387c5e1a03.jpg)

4. I removed the last entry (n++) but it crashed again

![01593182806_01007ef00011e000](https://user-images.githubusercontent.com/8191872/85870974-1283e080-b7ce-11ea-84df-094cb8bfe1ec.jpg)

## Crash Report
If you are running Atmosphere and the crash generated a report, please locate it in `/atmosphere/crash_reports` and either link or paste it here in a code-block.

https://pastebin.com/uScHi3Km

**Comment by 16BitWonder** [comment]
Significant changes have been made by now, including fixing a recent null-ref bug that was likely causing this crash.

If you run the latest release (v1.5.1 at the time of writing) and still encounter these crashes please open a new bug report.
